### ISSUE TITLE
[BUG] kunaon respon na error ajig?

### ISSUE THREAD

**Issue by TraFost** [masnormen/sunda.js#1]
respona kumaha kie mang " ᮝᮤᮂ, ᮌᮩᮜᮤᮞ᮪ ᮉᮚ᮪!"?
aing teh lieur anying, goblog.

hampura sakitu ge

@masnormen

**Comment by masnormen** [comment]
Hampura teu tiasa basa sunda.
Lagi ngelawak kah?
